# -*- coding: utf-8 -*-

# flake8: noqa

# Tags set to None of False will be ignored
# Tags set to True will be used as-is
# Tags set to a string will be replaced by that string
# Tags set to a list will be replaced with multiple tags

from __future__ import unicode_literals

TAGS_MAP = {u'1:2000': None,
 u'1:5000': None,
 u'25000': None,
 u'ACQUA, DERIVAZIONE IDRICA DI SOCCORSO, SIAT, SUAP, RNDT': u'Derivazione idrica di soccorso',
 u'ACQUA, DERIVAZIONE IDRICA, RESTITUZIONE IDRICA, SIAT, SUAP, RNDT': u'Restituzione idrica',
 u'Alvei': True,
 u'BIC': None,
 u'Biotopi comunali': True,
 u'Biotopi locali': True,
 u'Biotopi provinciali': True,
 u'Cadastral parcels': None,
 u'Comuni': True,
 u'Corine Land Cover': None,
 u'Direttiva Uccelli': None,
 u'Distribuzione della popolazione \xe2\x80\x94 demografia': None,
 u'Distribuzione della popolazione \u2014 demografia': None,
 u'Edifici': True,
 u'Elevazione': True,
 u'Geologia': True,
 u'Ghiacciai': True,
 u'Idrografia': True,
 u'Impianti agricoli e di acquacoltura': None,
 u'Mineral resources': None,
 u'Natura2000': None,
 u'Nomi geografici': True,
 u'Orto immagini': True,
 u'PUP': None,
 u'PUP, RNDT': None,
 u'PUP, RNDT,': None,
 u'PUP; RNDT': None,
 u'Parcelle catastali': 'Particelle catastali',
 u'Particelle catastali': True,
 u'RNDT': None,
 u'RNDT, attenzione identificatore pupvia': None,
 u'Regioni marine': None,
 u'Reti di trasporto': None,
 u'Riserve Naturali provinciali': None,
 u'Riserve locali': None,
 u'SIAT': None,
 u'SIAT, Grotte, Catasto grotte, Rilievi grotte, Cavit\xc3\xa0, Servizio Geologico, RNDT': u'Grotte',
 u'SIAT, Grotte, Catasto grotte, Rilievi grotte, Cavit\xe0, Servizio Geologico, RNDT': None,
 u'SIAT, Grotte, Rilievi grotte, Cavit\xc3\xa0, Servizio Geologico, RNDT': u'Grotte',
 u'SIAT, Grotte, Rilievi grotte, Cavit\xe0, Servizio Geologico, RNDT': None,
 u'SIAT, RNDT': None,
 u'SIAT, RNDT, Corine Land Cover, Copertura del suolo': u'Copertura del suolo',
 u'SIAT, RNDT, PGUAP': None,
 u'SIAT, RNDT, cave dismesse, vecchie cave': [u'Cave', u'Cave dismesse'],
 u'SIAT, RNDT, cave, piano cave': u'Cave',
 u'SIAT, RNDT, miniere dismesse, sotterraneo': u'Miniere dismesse',
 u'SIAT, RNDT, miniere, acque minerali, acque termali, concessioni': None,
 u'SIAT, RNDT, pozzi, sorgenti, acque minerali': [u'Pozzi',
                                                  u'Sorgenti',
                                                  u'Acque minerali'],
 u'SIAT, RNDT, viafer': None,
 u'SIAT, Terremoti, Stazioni sismiche, Eventi sismici, Servizio Geologico, RNDT': u'Terremoti',
 u'SIAT, ghiacciai, RNDT': None,
 u'SIAT, valanghe, RNDT': None,
 u'SIAT,SUAP, RNDT, ACQUA, DERIVAZIONE IDRICA': [u'Acqua',
                                                 u'Derivazione idrica'],
 u'SIC': None,
 u'Sedi': True,
 u'Servizi di pubblica utilit\xc3\xa0 e servizi amministrativi': None,
 u'Servizi di pubblica utilit\xe0 e servizi amministrativi': None,
 u'Siti': True,
 u'Siti protetti': True,
 u'UDF': None,
 u'UNESCO': True,
 u'Unit\xe0 amministrative': None,
 u'ZPS': None,
 u'accessi aree sciabili': None,
 u'acqua di rifiuto urbana': ['Acqua'],
 u'acque sotterranee': ['Acqua'],
 u'acque superficiali': ['Acqua'],
 u'aereoporti': 'Aeroporti',
 u'aeroporti': 'Aeroporti',
 u'agglomerato': None,
 u'agricol': 'Agricoltura',
 u'alberi monumentali': None,
 u'alta capacit\xc3\xa0': None,
 u'alta capacit\xe0': None,
 u'altimetria': None,
 u'altitudine': None,
 u'alvei': True,
 u'ambiti': None,
 u'archeolog': 'Archeologia',
 u'aree a bosco': True,
 u'aree a pascolo': True,
 u'aree agricole': True,
 u'aree espansione': True,
 u'aree estrattive': True,
 u'aree insediative produttive  servizi': True,
 u'aree produttive': True,
 u'aree protette': True,
 u'aree rispetto': True,
 u'aree rocciose': True,
 u'aree sciabili': True,
 u'aree servizi': True,
 u'aree, RNDT': None,
 u'asta fluviale': True,
 u'attrezzature': None,
 u'bacini': True,
 u'bacini, RNDT': 'Bacini',
 u'beni ambientali': True,
 u'beni architettonici': True,
 u'beni architettonici ed artistici': True,
 u'beni artistici': True,
 u'beni culturali': True,
 u'big city': None,
 u'biotopi': None,
 u'bosc': 'Boschi',
 u'boschi': True,
 u'boundaries': None,
 u'canali': True,
 u'carico generato': None,
 u'carta del paesaggio': True,
 u'carta tecnica': True,
 u'cartografia': True,
 u'catasto': True,
 u'cave': True,
 u'ceduo': None,
 u'censimento': None,
 u'centrali': None,
 u'centrali idroelettriche': None,
 u'centri abitati': None,
 u'centri commerciali': None,
 u'centri innovazione': None,
 u'centri storici': None,
 u'centri storici aggregati': None,
 u'centri turistici': None,
 u'ciclabili': u'Piste ciclabili',
 u'collegamenti funzionali': None,
 u'commercio': None,
 u'comprensori': None,
 u'comun': None,
 u'comune amministrativo': None,
 u'comuni': None,
 u'comuni  catastali': None,
 u'comuni amministrativi': None,
 u'comunit\xe0': None,
 u'comunit\xe0 di valle': True,
 u'condotte': None,
 u'confine': None,
 u'conoidi alluvionali': None,
 u'conservazione ambientale': None,
 u'corine land cover': None,
 u'corsi artificiali': True,
 u'corsi naturali': True,
 u'curve di livello': u'Curve di livello',
 u'curve livello': u'Curve di livello',
 u'depuratori': True,
 u'dipartimento foreste': None,
 u'direttiva europea HABITAT': None,
 u'direttiva europea abitat': None,
 u'dolomiti': True,
 u'economy': u'Economia',
 u'edifici pubblici': True,
 u'elementi geologici': True,
 u'elementi geomorfologici': True,
 u'elementi rappresentativi': True,
 u'elevation': None,
 u'environment': u'Ambiente',
 u'faglie': True,
 u'farming': None,
 u'farzione': None,
 u'ferrovia': 'Ferrovie',
 u'ferrovie': 'Ferrovie',
 u'ferrovie di progetto': ['Ferrovie'],
 u'fiume': 'Fiumi',
 u'fiumi': True,
 u'foreste': True,
 u'foreste demaniali': ['Foreste'],
 u'fosse': True,
 u'fronti di pregio': None,
 u'fustaia': True,
 u'gallerie': True,
 u'gas': True,
 u'geologia': True,
 u'geoscientificInformation': None,
 u'habitat': None,
 u'idrografia': True,
 u'idrografici': 'Idrografia',
 u'imageryBaseMapsEarthCover': None,
 u'impianti a fune': None,
 u'impianti di depurazione': None,
 u'impianti di risalita': None,
 u'impianti pubblici': None,
 u'impianto di depurazione': None,
 u'improduttivo': None,
 u'incendi': None,
 u'indice di funzionalit\xc3\xa0 fluviale': None,
 u'indice di funzionalit\xe0 fluviale': None,
 u'infrastrutture': None,
 u'inlandWaters': None,
 u'inquadramenti': True,
 u'inquadramenti di base': True,
 u'inquadramento': True,
 u'inquinamento': True,
 u'insediamenti': True,
 u'interporti': True,
 u'invariante': None,
 u'invarianti': None,
 u'istat': None,
 u'laghi': None,
 u'lago': None,
 u'limite provinciale': None,
 u'limiti': None,
 u'limiti espansione abitati': None,
 u'linee alta tensione': None,
 u'linee di livellazione': None,
 u'linee elettriche': None,
 u'livello': None,
 u'localit\xe0': None,
 u'location': None,
 u'mappe catastali': True,
 u"monitoraggio dell'acqua": None,
 u"monitoraggio qualita' acqua": None,
 u'nazionali': None,
 u'oceans': None,
 u'orografia': None,
 u'paesaggi di particolare pregio': None,
 u'paesaggio': None,
 u'paleoalvei': None,
 u'parchi naturali': None,
 u'pascoli': None,
 u'pascolo': None,
 u'patrimonio delle dolomiti': None,
 u'pericolosit\xc3\xa0': None,
 u'pericolosit\xe0': None,
 u'pertinenza': None,
 u'piano cave': True,
 u'piste': None,
 u'piste sci': True,
 u'planningCadastre': None,
 u'presenze': None,
 u'principale': None,
 u'principali': None,
 u'punti quotati': None,
 u'pup': None,
 u'pupagri': None,
 u'pupasc': None,
 u'pupbos': None,
 u'quadro unione': None,
 u"qualit\xc3\xa0 dell'acqua": None,
 u"qualit\xe0 dell'acqua": None,
 u'rete caposaldi': None,
 u'rete natura 2000': None,
 u'reti': None,
 u'reticolo chilometrico': None,
 u'rio': None,
 u'riserve naturali': u'Riserve naturali',
 u'rocce': None,
 u'rupi': None,
 u'rupi boscate': None,
 u'scritte': None,
 u'servizi': None,
 u'sezioni censimento': None,
 u'siat': None,
 u'sistema di collettamento': None,
 u'sistemi complessi di paesaggio': None,
 u'siti archeolog': u'Siti archeologici',
 u'siti di interesse comunitario': None,
 u'society': None,
 u'specchi': None,
 u'statistica': None,
 u'statistiche': None,
 u'stazioni forestali': u'Stazioni forestali',
 u'strade': None,
 u'structure': None,
 u'toponimi': u'Toponimi',
 u'toponomastica': None,
 u'toponomastica 1:25000': None,
 u'toponomastica1:50000': None,
 u'torrente': None,
 u'transportation': u'Trasporti',
 u'tutela': None,
 u'tutela ambientale': u'Tutela ambientale',
 u'tutele paesistiche': u'Tutela paesistica',
 u'uffici distrettuali forestali': None,
 u'uso del suolo': u'Uso del suolo',
 u'uso del suolo CORINE': u'Uso del suolo',
 u'uso del suolo corine': u'Uso del suolo',
 u'uso suolo': u'Uso del suolo',
 u'uso suolo reale': u'Uso del suolo',
 u'utilitiesCommunication': None,
 u'vegetazione': True,
 u'viabilit\xe0': True,
 u'viabilit\xe0 di progetto': True,
 u'viabilit\xe0 esistente': True,
 u'viabilit\xe0 ferroviaria': True,
 u'viabilit\xe0 forestale': True,
 u'zone di protezione speciale': False,
 u'ZSC, Zone Speciali di Conservazione': u'Zone speciali di conservazione',
 u'zone speciali conservazione, ZSC': u'Zone speciali di conservazione'}
